### ISSUE TITLE
《重新定义Spring Cloud实战》读者书评-收集ing

### ISSUE THREAD

**Issue by SoftwareKing** [SpringCloud/spring-cloud-code#1]
欢迎各位读者按照下面格式反馈读者书评
* 本书优点:xxxxx
* 本书不足:xxxx
* 第二版展望:xxxxx

**Comment by rhettpang** [comment]
书什么时候出版？网上没搜到

**Comment by SoftwareKing** [comment]
@rhettpang 目前在预售电子版，需要可以加我微信Software_King购买。

**Comment by edd1225** [comment]
这书加你微信就能买了吗

**Comment by SoftwareKing** [comment]
![image](https://user-images.githubusercontent.com/6858857/45793863-6d69d900-bcc6-11e8-9c16-f0748a06c379.png)

**Comment by SoftwareKing** [comment]
![image](https://user-images.githubusercontent.com/6858857/45793900-a2762b80-bcc6-11e8-848a-6a00073051f2.png)

**Comment by zuoziye1** [comment]
ch3-1-config-server 启动之后，再启动 eureka-server启动不了，我让我同事看，我同事说必须把server.port放在eureka-server的配置文件中才行。ch3-1 源码是不是有问题啊？求解答

**Comment by laiyy0728** [comment]
第五章。图 5-1 load balancer 文字描述错误

**Comment by laiyy0728** [comment]
在表 5-1 下方的介绍中，提到：ZoneAvoidanceRule 策略已经废弃掉了，现在的默认负载均衡是 RoundRobin。而在表 5-3 中，IRule 的默认实现类是 ZoneAvoidanceRule。这个是否有冲突？我理解的是，既然 ZoneAvoidanceRule 已经废弃了，那么默认的实现类应该是 RoundRobin？

**Comment by linwei007** [comment]
这本书前面几张写的非常好，是读过的基本springboot里面把关键点写的非常清楚地一本。但是第21章版本控制和灰度发布，写的太简单，就是个sample 结束完全不知其所以然。

**Comment by SoftwareKing** [comment]
@laiyy0728 @linwei007 @zuoziye1 更多内容解答，可以加我微信Software_King进微信群

**Comment by 2458991423** [comment]
也感觉21章有些简单，笼统，其他章节写的很好，源码，实战并存。

**Comment by xiaomalover** [comment]
> ch3-1-config-server 启动之后，再启动 eureka-server启动不了，我让我同事看，我同事说必须把server.port放在eureka-server的配置文件中才行。ch3-1 源码是不是有问题啊？求解答

你解决了吗？我也是同样的问题

**Comment by major2015** [comment]
内容太入门了，spring.io上全有啊。。。

**Comment by GreyZeng** [comment]
ch10-1的common项目应该少了一个依赖：
import org.apache.commons.lang.StringUtils;
这个报错了

**Comment by GreyZeng** [comment]
* 本书优点:内容较新，覆盖全面
* 本书不足:可以完善一下ch10-1的综合案例
* 第二版展望:介绍或者对比一下Service Mesh 技术和istio框架

**Comment by 826193310** [comment]
一开始就掉坑， 代码清单 ch2-1的pom.xml 中spring-cloud 的版本用 变量${spring-cloud.version}标识，而在仓库中却是直接填的版本信息，我觉得代码尽量贴全面一点咯

**Comment by upcwangying** [comment]
- 本书优点:内容较新，覆盖全面
- 本书不足:能不能添加一个所有配置的列表
- 第二版展望:加入Nacos、Sentinel等相关介绍；对比一下Service Mesh 技术和istio框架

**Comment by magaofeng2010** [comment]
配置书中讲的不全，得对着源码工程来才行

**Comment by magaofeng2010** [comment]
不过坑爬的多，懂得就越多，感谢作者

**Comment by xialutiya** [comment]
3-1的eureka-server要怎么启动的，直接启动总是默认端口8080，没有加载到config-server中的配置文件.我在eureka-server的配置文件里面加上了spring.profiles.active=peer1才能加载到eureka-server-peer1，但是peer2又要怎么加载.

**Comment by rhettpang** [comment]
搞毛啊，为什么每次都会抄送我------------------ 原始邮件 ------------------
发件人: "xialutiya"<notifications@github.com>
发送时间: 2019年7月18日(星期四) 上午8:22
收件人: "SpringCloud/spring-cloud-code"<spring-cloud-code@noreply.github.com>;
抄送: "rhettpang"<rhett.pang@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [SpringCloud/spring-cloud-code] 《重新定义Spring Cloud实战》读者书评-收集ing (#1)



3-1的eureka-server要怎么启动的，直接启动总是默认端口8080，没有加载到config-server中的配置文&#x4EF6;.我在eureka-server的配置文&#x4EF6;里面加上了spring.profiles.active=peer1才能加载到eureka-server-peer1，但是peer2又要怎么加载.
 
&mdash;

**Comment by zjs9609** [comment]
> 3-1的eureka-server要怎么启动的，直接启动总是默认端口8080，没有加载到config-server中的配置文件.我在eureka-server的配置文件里面加上了spring.profiles.active=peer1才能加载到eureka-server-peer1，但是peer2又要怎么加载.

你没有写controller吗,我现在遇到了一个问题就是起不了eureka-peer2

**Comment by SoftwareKing** [comment]
@zjs9609 里面有个readme文件，还有问题加我微信进书籍答疑群

**Comment by cghtom** [comment]
p505 ch21-3 的代码呢？

**Comment by cakin24** [comment]
第十三章灰度发布的Discovery项目是哪个版本啊？github上下载下来的项目会有登录认证这一步，有com.nepxion.discovery.console.desktop.ConsoleLogin.java这个文件，书中截图却没有这个文件，到底是哪个版本啊？

**Comment by cakin24** [comment]
建议把P503 页的Discovery项目的源码也加到github上，或者指定 https://github.com/Nepxion/Discovery的具体版本号，以及相关配置。以便于和21.3.2的项目调通。

**Comment by chengqiuming** [comment]
1 https://github.com/Nepxion/Discovery目前最早的版本是3.8.1 ，discovery-console-desktop子项目都有ConsoleLogin.java  这个文件，但书中截图却没这个文件，P503页无可操作性。
2 运行https://github.com/Nepxion/Discovery项目后会弹出认证框，输入用户名：admin  ，密码：admin，提示用户名和密码错误。
3 在ch21-1/ch21-1-discovery-console这个项目中加上 admin=admin还是报错。
4 屏蔽掉： ConsoleLogin consoleLogin = new ConsoleLogin();  consoleLogin.launch();跳过认证，进入主界面后，选择服务拓扑，还是报错，提示java.lang.IllegalArgumentException: {"timestamp":"2019-12-08T02:21:34.776+0000","status":404,"error":"Not Found","message":"No message available","path":"/console/groups"}
灰度发布这一题材很好，可就是调不通，哪位大侠能调通？
