### ISSUE TITLE
第8章-勘误列表汇总

### ISSUE THREAD

**Issue by SoftwareKing** [SpringCloud/spring-cloud-code#10]

**Comment by renlei413326889** [comment]
ch8-1-zuul-server：PostFilter里面乱码问题依然存在
//处理返回中文乱码
ctx.getResponse().setCharacterEncoding("UTF-8"); -->
//获取上下文中保存的responseBody
String responseBody = ctx.getResponseBody();
//如果responseBody不为空，则说明流程有异常发生
if (null != responseBody) {
			//设定返回状态码
			ctx.setResponseStatusCode(500);
			//替换响应报文
	        ctx.setResponseBody(responseBody);
}
设置为：ctx.getResponse().setContentType("text/json;charset=UTF-8"); 不乱码
