### ISSUE TITLE
第4章勘误汇总

### ISSUE THREAD

**Issue by liuxiany** [SpringCloud/spring-cloud-code#14]
第四章 Spring Cloud Feign
4.1.3 Feign的工作原理  小节（第78页）。两处地方，应该是@FeignClient 而不是 @FeignClients
![4 1 3](https://user-images.githubusercontent.com/41094939/47031495-8620be00-d1a2-11e8-98c4-2bce22ae9a78.png)

**Comment by SoftwareKing** [comment]
@liuxiany 这个很早以前已经勘误，进答疑群交流，加微信Software_King
