### ISSUE TITLE
Hystrix这章写的什么玩意儿？

### ISSUE THREAD

**Issue by shizhengqiang** [SpringCloud/spring-cloud-code#17]
前几章都挺好的，到了第六章Hystrix，例子跑不起来，报：找不着方法 org.HdrHistogram.Histogram.<init>(I)V，而且写的一点都不细致，这本书最大的败笔就是这章！

**Comment by zhudemingGitHub** [comment]
@shizhengqiang 你好，给你带来的烦恼很抱歉，请问下，是哪一个工程不行呢？我这边调试下。另外哪部分写的不太细致还请帮忙说下，下次我们注意下，不好意思。
