### ISSUE TITLE
gateway疑问

### ISSUE THREAD

**Issue by ayanjoyful** [SpringCloud/spring-cloud-code#19]
gateway:
        discovery:
          locator:
          #开启服务发现路由匹配规则
            enabled: true
            filters:
            - name: Hystrix
              args:
                name: default
                fallbackUri: forward:/fallback

这么配置filters报错,为什么discovery 配置filters不生效.

**Comment by SoftwareKing** [comment]
进答疑群交流，加微信Software_King，配置错误请参考书中的case。

**Comment by SoftwareKing** [comment]
@ayanjoyful 进答疑群交流，加微信Software_King，配置错误请参考书中的case。
