### ISSUE TITLE
3.5.1 Eureka Server 在线扩容 118页 报错解决

### ISSUE THREAD

**Issue by sunshineshenjin** [SpringCloud/spring-cloud-code#20]
eureka-server-peer1.yml 中配置有问题
启动一个eureka server配置有问题（禁止自注册）
改为：
 register-with-eureka: false
    fetch-registry: false

**Comment by SoftwareKing** [comment]
@sunshineshenjin 没有问题，有需要的话，进答疑群，加微信Software_King,答疑群回答了10多次。姿势不对。
