### ISSUE TITLE
oauth2-zull疑问

### ISSUE THREAD

**Issue by cel105302** [SpringCloud/spring-cloud-code#21]
![image](https://user-images.githubusercontent.com/32325588/49909986-0a01d880-febc-11e8-8aee-9f633eb08488.png)
这个zuul和oauth2整合权限登陆后报了这个错误，我用的cloud版本是Greenwich.M3，这个怎么处理，有大佬遇到过吗，谢谢

**Comment by cel105302** [comment]
![image](https://user-images.githubusercontent.com/32325588/49910080-5d742680-febc-11e8-86f3-f4a2b4f0c5d7.png)

**Comment by SoftwareKing** [comment]
@cel105302 书中用的是F版。G版可以自己解决一下，进答疑群交流，加微信Software_King

**Comment by cel105302** [comment]
@SoftwareKing好的，谢谢
