### ISSUE TITLE
对网关gateway的疑问

### ISSUE THREAD

**Issue by alibabazhang** [SpringCloud/spring-cloud-code#23]
@Bean("custom_route")
    public RouteLocator customerRouteLocator(RouteLocatorBuilder builder) {
        return builder.routes()
                .route(r -> r.path("/test/customFilter")
                        .filters(f -> f.filter(new CustomGatewayFilter()).stripPrefix(1))
                        .uri("http://localhost:7001/test")
                        .order(0)
                        .id("custom_filter")
                )
                .build();
    }
我在看书过程中发现：/test/customFilter 并不能路由到http://localhost:7001/test路径下，会报404错误，通过日志跟踪发现，gateway找的是http://localhost:7001/test/customFilter，与书中案例出现冲突！ 望解惑！！谢谢！

**Comment by SoftwareKing** [comment]
@alibabazhang 加我微信Software_King进答疑群交流，
