### ISSUE TITLE
Feign文件上传500错误

### ISSUE THREAD

**Issue by wuxiaobo000111** [SpringCloud/spring-cloud-code#32]
按照书中代码来做,并不会实现文件上传，会报500异常。

![360截图20190421103254102](https://user-images.githubusercontent.com/20573340/56464670-d8c48680-6420-11e9-8c92-4c94645a8a1a.jpg)
后台错误日志如下:
![360截图20190421103332067](https://user-images.githubusercontent.com/20573340/56464674-f396fb00-6420-11e9-9bf8-c5e2090fb53c.jpg)

**Comment by wuxiaobo000111** [comment]
原因是FeignUploadController返回值的问题,直接返回f return file.getOriginalFilename();直接报500，希望能够改正一下。

**Comment by SoftwareKing** [comment]
@wuxiaobo000111 书中实现了文件上传，返回了原文件名称，加我微信Software_King进读者答疑群交流。
