### ISSUE TITLE
swagger与gateway整合一章

### ISSUE THREAD

**Issue by huaihkiss** [SpringCloud/spring-cloud-code#35]
书中的案例 通过定义一个filter 将X-Forwarded-Prefix添加到header中 但是实际发现greenwich版本中 这个header被gateway自动添加进去了 这种情况下发现swagger取api-docs的时候baseUrl有错误 这个是否是书中老版本的原因

**Comment by SoftwareKing** [comment]
@huaihkiss 书中的案例是基于F版的，G版兼容性问题需要自己解决。或者加我微信，沟通处理Software_King
