### ISSUE TITLE
第3章-勘误列表汇总

### ISSUE THREAD

**Issue by SoftwareKing** [SpringCloud/spring-cloud-code#7]
![image](https://user-images.githubusercontent.com/6858857/46340952-90eb3700-c669-11e8-8e50-eb0b8d89fe9f.png)

**Comment by tangchunbo** [comment]
![_20181002180531](https://user-images.githubusercontent.com/20239172/46342650-e9bcce80-c66d-11e8-9561-c35ba8ecc208.png)
